backend:
  name: git-gateway
  branch: main

media_folder: "public/upload"
public_folder: "/"

site_url: https://blog.ignaciocarrasco.cl/

media_library:
  name: cloudinary
  config:
    cloud_name: <YOUR_CLOUD_NAME_HERE>
    api_key: <YOUR_API_KEY_HERE>

# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields: 
    - { name: "metaTitle", label: "SEO Title", widget: "string", default: "{{ title }}", required: true }
    - { name: "metaDescription", label: "SEO Description", widget: "string", pattern: [".{20,160}", "between 20 and 160 characters"], required: true, hint: "must be between 20 and 160 characters" }
    - { name: "metaImage", label: "SEO image", widget: "image"}
    - { name: "keywords", label: "keywords", widget: "string", hint: "keywords are comma seperated", required: false }

collections:
  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/pages/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - { name: "featuredPosts", label: "Featured Posts", widget: "relation", collection: "blog", search_fields: ["title"], value_field: "title", multiple: true, required: false }
          - *seo

  # BLOG POSTS COLLECTION
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "date", label: "Publish Date", widget: "datetime", default: "", required: true }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "summary", label: "Summary", widget: "text", required: false }
      - { name: "body", label: "Body", widget: "markdown", required: true }
      - { name: "author", label: "Author", widget: "string", default: "Your Name", required: true }
      - { name: "categories", label: "Categories", widget: "list", field: { name: "category", label: "Category", widget: "string" }, required: false }
      - { name: "tags", label: "Tags", widget: "list", field: { name: "tag", label: "Tag", widget: "string" }, required: false }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - *seo